-- AuditLogs Table
CREATE TABLE AuditLogs (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    TableName NVARCHAR(100) NOT NULL,
    Operation NVARCHAR(50) NOT NULL,
    RecordId UNIQUEIDENTIFIER NOT NULL,
    OldData NVARCHAR(MAX),
    NewData NVARCHAR(MAX),
    CreatedBy NVARCHAR(100) NOT NULL,
    CreatedAt DATETIME NOT NULL DEFAULT GETUTCDATE()
);